Repository MahabhoiAryan/HacktoberFest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create python file
  currency.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#2 Web Scraping to Create a Dataset using Python
  webscrappig.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#3 Number Guessing Game using Python
  numberguess.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#4 Snake_game
  Snake_game.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#5 Created Railway Booking Python file
  railwaybook.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#6 Create Pattern.java
  pattern.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#7 HacktoberFest Brand Logo
  Hfest-Logo-2-Color-Manga@2x.png
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#8 Create mergesort
  mergesort.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#9 Create anagram
  anagram.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#10 Create tictactoe
  tictactoe.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#13 Added basic python codes for beginners
  Python Codes/Built-in Functions/container-functions.py
  Python Codes/Built-in Functions/numeric-functions.py
  Python Codes/Built-in Functions/string-functions.py
  Python Codes/Classes/class-methods.py
  Python Codes/Classes/class.py
  Python Codes/Classes/constructor.py
  Python Codes/Classes/inheritance.py
  Python Codes/Classes/iterator.py
  Python Codes/Exceptions/exceptions.py
  Python Codes/Exceptions/exceptions_.py
  Python Codes/File IO/berlin-copy.jpg
  Python Codes/File IO/berlin.jpg
  Python Codes/File IO/copy-bin.py
  Python Codes/File IO/copy-text.py
  Python Codes/File IO/lines-copy.txt
  Python Codes/File IO/lines.txt
  Python Codes/File IO/openFile.py
  Python Codes/Functions/decorators.py
  Python Codes/Functions/function-definition.py
  Python Codes/Functions/generators.py
  Python Codes/Functions/keyword-arguments.py
  Python Codes/Functions/variable-arguments.py
  Python Codes/Modules/modules.py
  Python Codes/Modules/mymodule-test.py
  Python Codes/Modules/mymodule.py
  Python Codes/Operators/arithmatic-operators.py
  Python Codes/Operators/bitwise-operators.py
  Python Codes/Operators/boolean-operators.py
  Python Codes/Operators/comparison-operators.py
  Python Codes/String Objects/formatting-strings.py
  Python Codes/String Objects/split-join.py
  Python Codes/String Objects/string-methods.py
  Python Codes/Structured Data/dictionary.py
  Python Codes/Structured Data/list-comprehension.py
  Python Codes/Structured Data/lists-tuples.py
  Python Codes/Structured Data/sets.py
  Python Codes/Types and Values/bool-types.py
  Python Codes/Types and Values/numeric-types.py
  Python Codes/Types and Values/sequence.py
  Python Codes/Types and Values/strings.py
  Python Codes/Types and Values/type-id.py
  Python Codes/Types and Values/types.py
  Python Codes/hello.py
  Python Codes/loops.py
  Python Codes/ternary.py
  Python Codes/version-working.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#14 Create puzzle
  Puzzle.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#15 Added folders
  Contributors/text.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#18 Create amn.py
  amn.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#19 sheryl.py
  sheryl.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#20 samiksha.py
  samiksha.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#21 create aditi.py
  aditi.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#17 Add Guess Number App file
  Java Codes/GuessNumberApp.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#16 Added file for recursive factorial
  Contributors/recursive_factorial.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#12 Create graphics.py
  Graphics.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#22 hi
  Contributors/python.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#25 Create simple_calculator.py
  simple_calculator.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#27 sort added
  Python Codes/bubblesort.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#28 numsys.py
  numsys.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#29 cntdwn.py
  cntdwn.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#30 haseeb.py
  haseeb.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#31 factorial.py
  factorial.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#32 Create shriyu.py
  shriyu.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#33 swap.py
  swap.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#34 leapyear.py
  leapyear.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#35 printing.py
  printing.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#37 squareroot.py
  squareroot.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#38 Added Simple CNN
  simpleCNN.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#39 CPF validator
  lalaland.html
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#40 hacktoberfest2022
  Reverse-stack_recursion.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#43 python
  Contributors/demo.txt
  Contributors/helloworld.py
  Contributors/text.md
  Python Codes/bubblesort.py
  Reverse-stack_recursion.py
  addition.py
  cntdwn.py
  factorial.py
  fibonacci.py
  haseeb.py
  lalaland.html
  leapyear.py
  numsys.py
  printing.py
  shriyu.py
  simpleCNN.py
  simple_calculator.py
  squareroot.py
  swap.py
  swap.txt
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#44 Added leetcode solution
  Java Codes/WordSearch.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#46 leetcode solution
  Java Codes/TargetSum.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#48 created password generator
  password_generator.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#49 text file
  swap1.txt
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#50 Add a program to encrypt strings in java
  Java Codes/EncryptString.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#51 2413 SmallestEvenMultiple
  Java Codes/2413.SmallestEvenMultiple.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#64 New file aryan
  Test1.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#52 simple calculator using java switch case
  Java Codes/calculator_using_java.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#53 HACKTOBERFEST2022
  SHFIUDHFSUYID
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#55 Create emirp.java
  Java Codes/emirp.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#59 Added quadratic equation,py
  quadratic_equation.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#60 Added Bus Game.py
  busgame.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#61 Added Monty Hall Stimulation program
  montyhall.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#62 Simple Python Cipher
  cipher.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#63 Created a new Directory for C++ lovers
  C++ Codes/Fizz_Buzz.cpp
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#65 Added Prime Number Code in Python
  Python Codes/primenumber.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#69 Create name1.py
  name1.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#68 added rock paper scissors GUI Game
  Rock_paper_scissors-GUI/main.py
  Rock_paper_scissors-GUI/paper.gif
  Rock_paper_scissors-GUI/scissors.gif
  Rock_paper_scissors-GUI/stone.gif
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#66 Create Comb_Sort.py
  Python Codes/Comb_Sort.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#70 Bubble
  Baner. Py
  Banker. Py
  Bubble. Py
  Limit. Py
  Quick. Py
  Range. Py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#71 linear_search.cpp
  DSA in CPP/Recursion/linear_search.cpp
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#72 Create RockPaperScissor.java
  Java Codes/RockPaperScissor.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#73 Bubble sort
  Bubble sort.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#74 Rock_paper_scissor
  Java Codes/Rock_paper_scissor.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#76 Added NQueens Program
  Java Codes/NQueens.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#77 Hacktoberfest2022
  Java_sum.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#78 Hacktoberfest
  C++.cpp
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#79 hacktoberfest2022
  divyansh65.java
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#80 added basic calculator program in python
  calculator.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#83 Number Arranging in python
  Contributors/Sorting.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#85 Time Machine in Python
  Contributors/time.py
Labels: Hacktoberfest2022, hacktoberfest-accepted, HACKTOBERFEST2022-ACCEPTED

#86 C++ Program to reverse number
  Basic Programs/C++/Reverse_a_Number.cpp
Labels: Hacktoberfest2022, hacktoberfest-accepted

#87 hacktoberfest2022
  binaryrec12.java
Labels: hacktoberfest-accepted

#88 Create warshall.java
  warshall.java
Labels: hacktoberfest-accepted

#89 hacktoberfest2022
  Java Codes/rotate_matrix.java
Labels: hacktoberfest-accepted

#90 Guess a Number
  GuessNumber.py
Labels: hacktoberfest-accepted

#91 hacktoberfest2022
  rotate_matrix.java
Labels: hacktoberfest-accepted

#56 Create code.py
  code.py
Labels: hacktoberfest-accepted

#93 Create duplicateChar.java
  duplicateChar.java
Labels: hacktoberfest-accepted

#94 Create Reflection C#
  Reflection C#
Labels: hacktoberfest-accepted

#95 Hacktober2
  SinglyLinkedList.c
Labels: hacktoberfest-accepted

#96 added quick sort algorithm
  Java Codes/QuickSort.java
Labels: hacktoberfest-accepted

#98 Creating Testing in c
  testing.c
Labels: hacktoberfest-accepted
